### PR TITLE
Update fr-fr.yml

### PR DESCRIPTION
**Pull request by FSOL-XDAG**
Spelling correction

### CODE REVIEW

**Review by FSOL-XDAG — COMMENTED** [review]
* Untranslated texts remaining in English
* Enhanced translation
* Still spelling correction

**Review by FSOL-XDAG — COMMENTED** [review]
* Last correction

**Review by FSOL-XDAG — COMMENTED** [review]
* Last change

**Review by FSOL-XDAG — COMMENTED** [review]
More spelling corrections.

**Review by WiIIiam278 — APPROVED** [review]

**Pull request merged**
