### PR TITLE
Parallel tp command

### PR DESCRIPTION
**Pull request by Emibergo02**
A command to switch servers but mantaining the same Location
Very useful for distributed systems

### CODE REVIEW

**Comment by Emibergo02** [comment]
Already tested and working

**Review by WiIIiam278 — CHANGES_REQUESTED** [review]
I'm cool with adding this & can see the use &mdash; but given that it's _fairly_ limited in terms of being only useful on servers with mirror world instances (and could accordingly be rather dangerous), let's have it be disabled by default.

Code looks good, just add it to the disabled commands section by default and document that it is disabled accordingly (don't forget to update the sample config in `docs/Config-Files.md` too)

**Comment by WiIIiam278** [comment]
Oh this fails tests because the test suite doesn't account for commands being disabled.

I think I'm gonna put this one on ice for a bit just due to how niche a command it is.

**Comment by WiIIiam278** [comment]
I've decided to decline this FR after a bit of consideration to keep the plugin lean on features limited in scope to only certain setups / use cases

**Pull request closed without merging**
