### PR TITLE
🥖 Translation to French

### PR DESCRIPTION
**Pull request by Funasitien**
This pull request add french translations to Husk _Homes_ *.
Still WIP

### CODE REVIEW

**Comment by WiIIiam278** [comment]
Hey-this file is blank and this is the HuskHomes repository (not HuskTowns) - is this intended?

**Comment by Funasitien** [comment]
Yeah, as I use these two plugins I mix it a bit. I originaly wanted to make both, but HuskTown have alerady one. And the file is blank due to an error with github on mobile...

**Comment by WiIIiam278** [comment]
@Funasitien When you're done, be sure to remove the extra spaces between lines in the locales file. Then, go right ahead and convert the PR from draft

**Comment by Funasitien** [comment]
Finally finished, I made the adjustment you asked and check if any of the `'` was breaking the yaml syntaxe. Should be ok

**Review by WiIIiam278 — APPROVED** [review]

**Pull request merged**
